import React from 'react';
import { useApp } from '../context/AppContext';
import { FileText, Shield, AlertTriangle, ArrowLeft, CheckCircle2 } from 'lucide-react';

export const TermsPage: React.FC = () => {
  const { setCurrentView } = useApp();

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-8">
      {/* Back button */}
      <div>
        <button
          onClick={() => setCurrentView('landing')}
          className="inline-flex items-center gap-1.5 text-xs font-semibold text-slate-600 hover:text-slate-900 transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>Back to Home</span>
        </button>
      </div>

      {/* Header */}
      <div className="border-b border-slate-200 pb-6 space-y-2">
        <div className="inline-flex items-center gap-2 rounded-full border border-sky-200 bg-sky-50 px-3 py-1 text-xs font-semibold text-sky-800">
          <FileText className="w-3.5 h-3.5 text-sky-700" />
          <span>Operating Agreement</span>
        </div>
        <h1 className="text-3xl font-extrabold text-slate-900 tracking-tight">
          Terms and Conditions of Use
        </h1>
        <p className="text-xs text-slate-500">
          Effective as of October 2026 • Governing Use of the AquaGuard Platform
        </p>
      </div>

      {/* Terms Content */}
      <div className="space-y-6 text-xs text-slate-700 leading-relaxed">
        <section className="space-y-2">
          <h2 className="text-sm font-bold text-slate-900">1. Acceptance of Terms</h2>
          <p>
            By accessing or operating the AquaGuard groundwater monitoring and management portal, you agree to comply with and be bound by these Terms and Conditions. If you do not agree, do not access the platform.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-sm font-bold text-slate-900">2. Permitted Purpose and Operational Scope</h2>
          <p>
            AquaGuard is designed for authorized water district personnel, hydrologists, municipal utility managers, agricultural associations, and environmental research partners. The platform facilitates:
          </p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Subsurface groundwater elevation tracking and drawdown monitoring.</li>
            <li>In-situ multi-parameter water quality screening.</li>
            <li>Hydraulic pipeline mass-balance leak identification.</li>
            <li>Cooperative aquifer recharge and watershed conservation planning.</li>
          </ul>
        </section>

        <section className="space-y-2">
          <h2 className="text-sm font-bold text-slate-900">3. Scientific Telemetry & Regulatory Disclaimers</h2>
          <div className="rounded-xl border border-amber-200 bg-amber-50/70 p-3.5 text-amber-900 space-y-1">
            <p className="font-bold">Crucial Safety Protocol:</p>
            <p>
              In-situ electronic sensors provide indicative operational telemetry and statistical anomaly screening. Telemetry readings cannot confirm potability or rule out unmeasured contaminants. Statutory compliance decisions and drinking safety declarations require certified physical sampling and ISO 17025 accredited laboratory assays (EPA, WHO, BIS, or equivalent local standards).
            </p>
          </div>
        </section>

        <section className="space-y-2">
          <h2 className="text-sm font-bold text-slate-900">4. Anomaly Alerts & Ethical Attribution</h2>
          <p>
            All anomaly alerts generated by AquaGuard (such as unusual flow drawdowns or night-time extraction surges) represent statistical mathematical departures from historic baseline curves. They do not constitute legal accusations of illegal abstraction or confirmed equipment sabotage. Users are required to execute on-site verification before initiating enforcement procedures.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-sm font-bold text-slate-900">5. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by applicable environmental law, AquaGuard and its system maintainers shall not be liable for indirect, incidental, or consequential damages resulting from sensor calibration drift, third-party network outages, delayed field inspections, or unmitigated aquifer drawdowns.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-sm font-bold text-slate-900">6. Platform Governance and Amendments</h2>
          <p>
            We reserve the right to refine monitoring algorithms, sensor threshold configurations, and these Terms as environmental regulatory guidelines evolve. Continued use of the platform after updates indicates acceptance of revised terms.
          </p>
        </section>
      </div>

      {/* Return button */}
      <div className="pt-6 border-t border-slate-200">
        <button
          onClick={() => setCurrentView('dashboard')}
          className="px-5 py-2.5 rounded-xl text-xs font-semibold bg-sky-700 hover:bg-sky-800 text-white transition-colors"
        >
          Return to Dashboard
        </button>
      </div>
    </div>
  );
};
